export type IconNames =
  | "icon-moon-01"
  | "icon-sun"
  | "icon-user-01"
  | "icon-users-01"
  | "icon-settings-01"
  | "icon-log-out-01"
  | "icon-home-02"
  | "icon-book-open-01"
  | "icon-x-close"
  | "icon-menu-03"
  | "icon-plus"
  | "icon-folder"
  | "icon-trash-01"
  | "icon-eye"
  | "icon-eye-off"
  | "icon-edit-03"
  | "icon-search-refraction";
